{
 "title": "GPU load",
 "tags": [ "grope" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(gpumon_engine_usage,node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Frequency",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rotmhz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg (gpumon_frequency{type=\"actual\",node=~\"^$node$\"}) by (node)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Power",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg (gpumon_power{node=~\"^$node$\", type=\"gpu\"}) by (type, node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "clients",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (gpumon_clients_count{node=~\"^$node$\"}) by (name, node)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Load",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (engine) (gpumon_engine_usage{attrib=\"busy\", node=~\"^$node$\"})",
     "legendFormat": "{{engine}}"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (engine) (gpumon_engine_usage{attrib=\"busy\", node=~\"^$node$\"})",
     "legendFormat": "{{engine}}"
    }
   ]
  },
  {
   "title": "IMC bandwidth",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg (gpumon_imc_read{node=~\"^$node$\"}) by (node)   ",
     "legendFormat": "read"
    },
    {
     "expr": "avg (gpumon_imc_write{node=~\"^$node$\"}) by (node)",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "IMC bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "expr": "avg (gpumon_imc_read{node=~\"^$node$\"}) by (node)   ",
     "legendFormat": "read"
    },
    {
     "expr": "avg (gpumon_imc_write{node=~\"^$node$\"}) by (node)",
     "legendFormat": "write"
    }
   ]
  }
 ]
}