name: build

on:
  push:
    branches:
      - main

jobs:
  test:
    uses: clambin/workflows/.github/workflows/test.yaml@main
    secrets:
      codecov-token: ${{ secrets.CODECOV_TOKEN }}
  build:
    needs:
      - test
    uses: clambin/workflows/.github/workflows/build.yaml@main
    with:
      dockerfile: Dockerfile
      image: ghcr.io/clambin/intel-gpu-exporter
