name: Build
on:
  push:
    branches:
      - main
      - refactor
  workflow_call:
    inputs:
      tags:
        type: string
        required: false
        default: |
          type=sha
permissions:
  contents: read
  packages: write
jobs:
  test:
    uses: ./.github/workflows/test.yaml
  build:
    needs:
      - test
    uses: clambin/workflows/.github/workflows/build.yaml@docker
    with:
      image: ghcr.io/clambin/intel-gpu-exporter
      tags: "${{ inputs.tags || 'type=sha' }}"
      platforms: linux/amd64
